"""Seed all 414 CLET Master Checklist items. Called on startup if table is empty."""
import uuid
from sqlalchemy import select
from app.models import ChecklistItem

# (section_number, section_title, subsection, item_text, is_new, directorate)
CHECKLIST_DATA = [
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Legal Foundation', 'Gazette Legal Education Reform Act (Act 1170)', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Legal Foundation', 'Publish Act in Ghana Gazette', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Legal Foundation', 'Confirm Commencement Date of Act', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Legal Foundation', 'Establish CLET as statutory body under the Act', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Legal Foundation', 'Issue commencement notice where applicable', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Legal Foundation', 'Establish transitional governance arrangements', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Legal Foundation', 'Transfer legal authority from GSL to CLET as prescribed', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Legal Foundation', "File certified copy with Registrar-General's Department", True, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Legal Foundation', 'Prepare transitional legal handover schedule', True, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governing Board', 'Constitute Governing Board', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governing Board', 'Obtain Presidential/Ministerial appointment letters', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governing Board', 'Vet and approve Board Members', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governing Board', 'Inaugurate Governing Board', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governing Board', 'Conduct Board orientation', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governing Board', 'Establish Board Secretariat', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governing Board', 'Adopt Board Charter', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governing Board', 'Establish Board Committees', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governing Board', 'Approve Board calendar', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governing Board', 'Appoint Board Secretary', True, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governing Board', 'Establish conflict-of-interest declaration register', True, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governing Board', 'Publish Board composition in Ghana Gazette', True, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governance Instruments', 'Corporate Governance Charter', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governance Instruments', 'Delegation of Authority Framework', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governance Instruments', 'Institutional Governance Manual', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governance Instruments', 'Board Operations Manual', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governance Instruments', 'Committee Terms of Reference', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governance Instruments', 'Risk Management Framework', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governance Instruments', 'Internal Control Framework', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governance Instruments', 'Compliance Framework', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governance Instruments', 'Ethics and Conduct Policy', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governance Instruments', 'Whistleblower Protection Policy', True, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governance Instruments', 'Freedom of Information (RTI) Policy', True, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Governance Instruments', 'Anti-Corruption & Integrity Policy', True, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Statutory Instruments', 'Common Seal Design', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Statutory Instruments', 'Common Seal Production', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Statutory Instruments', 'Common Seal Registration', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Statutory Instruments', 'Seal Custody Procedures', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Statutory Instruments', 'Seal Usage Register', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Statutory Instruments', 'Official Statutory Registers', False, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Statutory Instruments', 'Register of Members / Enrolled Lawyers Register', True, 'DG'),
    (1, 'LEGAL ESTABLISHMENT & STATUTORY ACTIVATION', 'Statutory Instruments', 'Legislative Instruments (LI) drafting as required under Act 1170', True, 'DG'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Identity', 'Official CLET Logo', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Identity', 'Secondary Logo Variants', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Identity', 'Monochrome Versions', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Identity', 'Directorate Logos', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Identity', 'Sub-brand Architecture', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Identity', 'Brand Identity Guidelines', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Identity', 'Brand Manual', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Identity', 'Typography Standards', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Identity', 'Colour Standards', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Identity', 'Iconography Standards', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Identity', 'Photography Style Guide', True, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Identity', 'Tone of Voice / Editorial Style Guide', True, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Stationery', 'Letterheads (Standard & Confidential)', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Stationery', 'Envelopes', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Stationery', 'Business Cards', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Stationery', 'Compliment Slips', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Stationery', 'Memo Templates', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Stationery', 'Policy Templates', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Stationery', 'Report Templates', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Stationery', 'Meeting Templates', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Stationery', 'Certificate Templates', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Stationery', 'Citation Templates', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Stationery', 'Accreditation Templates', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Stationery', 'Press Release Templates', True, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Stationery', 'Briefing Note Templates', True, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Corporate Stationery', 'Formal Correspondence Templates (including statutory notices)', True, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Digital Brand Assets', 'Email Signature Templates', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Digital Brand Assets', 'PowerPoint Templates', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Digital Brand Assets', 'Word Templates', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Digital Brand Assets', 'Social Media Templates', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Digital Brand Assets', 'Website Assets', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Digital Brand Assets', 'Event Branding Kit', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Digital Brand Assets', 'Roll-up Banners', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Digital Brand Assets', 'Pull-up Banners', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Digital Brand Assets', 'Signage Package', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Digital Brand Assets', 'Corporate Photography Library', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Digital Brand Assets', 'Branded Document Cover Pages', True, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Digital Brand Assets', 'E-certificate Design Templates', True, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Multimedia Assets', 'Logo Sting (animated)', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Multimedia Assets', 'Motion Graphics Package', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Multimedia Assets', 'Intro Video', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Multimedia Assets', 'Corporate Profile Video', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Multimedia Assets', 'Promotional Videos', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Multimedia Assets', 'Brand Sound Identity', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Multimedia Assets', 'Explainer Video – CLET mandate & functions', True, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Multimedia Assets', 'Legal Education Reform Campaign Video', True, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Intellectual Property', 'Copyright Registration', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Intellectual Property', 'Trademark Registration', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Intellectual Property', 'Brand Protection Framework', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Intellectual Property', 'Asset Ownership Documentation', False, 'CCP'),
    (2, 'INSTITUTIONAL IDENTITY & BRANDING', 'Intellectual Property', 'Domain Name Portfolio Registration & Protection', True, 'CCP'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Headquarters', 'Secure Office Premises', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Headquarters', 'Office Lease / Allocation Agreement', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Headquarters', 'Office Renovation', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Headquarters', 'Office Furnishing', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Headquarters', 'Executive Offices', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Headquarters', 'Board Room', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Headquarters', 'Meeting Rooms', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Headquarters', 'Reception Area', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Headquarters', 'Records Room', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Headquarters', 'Server Room / Secure ICT Room', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Headquarters', 'Dedicated Training / CBT Room', True, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Headquarters', 'Staff Welfare Facilities (kitchen, prayer room, first aid)', True, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Headquarters', 'Health & Safety Assessment', True, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Headquarters', 'Office Inventory Register', True, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Office Identity', 'Office Signage', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Office Identity', 'External Signage', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Office Identity', 'Internal Wayfinding', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Office Identity', 'Reception Branding', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Office Identity', 'Car Park Branding / Directional Signage', True, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Official Address', 'Physical Office Address', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Official Address', 'Ghana Post GPS Address', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Official Address', 'Postal Address Registration', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Official Address', 'Public Publication of Address', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Contact Channels', 'Main Telephone Line', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Contact Channels', 'Customer Service Line', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Contact Channels', 'Contact Centre Setup', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Contact Channels', 'Institutional WhatsApp Business Line', False, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Contact Channels', 'Fax Number (where required by government protocol)', True, 'SFL'),
    (3, 'PHYSICAL OFFICE ESTABLISHMENT', 'Contact Channels', 'Emergency / Out-of-Hours Contact Protocol', True, 'SFL'),
    (4, 'DIGITAL LOCATION PRESENCE', 'Maps Registration', 'Google Maps', False, 'DTI'),
    (4, 'DIGITAL LOCATION PRESENCE', 'Maps Registration', 'Apple Maps', False, 'DTI'),
    (4, 'DIGITAL LOCATION PRESENCE', 'Maps Registration', 'Bing Maps', False, 'DTI'),
    (4, 'DIGITAL LOCATION PRESENCE', 'Maps Registration', 'Waze', False, 'DTI'),
    (4, 'DIGITAL LOCATION PRESENCE', 'Maps Registration', 'OpenStreetMap', False, 'DTI'),
    (4, 'DIGITAL LOCATION PRESENCE', 'Maps Registration', 'HERE Maps', False, 'DTI'),
    (4, 'DIGITAL LOCATION PRESENCE', 'Maps Registration', 'ArcGIS', False, 'DTI'),
    (4, 'DIGITAL LOCATION PRESENCE', 'Maps Registration', 'Ghana Post GPS', False, 'DTI'),
    (4, 'DIGITAL LOCATION PRESENCE', 'Maps Registration', 'NITA Government Directory', False, 'DTI'),
    (4, 'DIGITAL LOCATION PRESENCE', 'Location Verification', 'Verified Office Pin', False, 'DTI'),
    (4, 'DIGITAL LOCATION PRESENCE', 'Location Verification', 'Verified Contact Information', False, 'DTI'),
    (4, 'DIGITAL LOCATION PRESENCE', 'Location Verification', 'Verified Opening Hours', False, 'DTI'),
    (4, 'DIGITAL LOCATION PRESENCE', 'Location Verification', 'Verified Directions', False, 'DTI'),
    (4, 'DIGITAL LOCATION PRESENCE', 'Location Verification', 'Ownership Claims Completed on all platforms', False, 'DTI'),
    (4, 'DIGITAL LOCATION PRESENCE', 'Location Verification', 'Accessibility information published (disability-friendly entry etc.)', True, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Government Digital Identity', 'Register clet.gov.gh', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Government Digital Identity', 'Reserve alternate domains (clet.gov.gh, clet.edu.gh, clet.org.gh)', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Government Digital Identity', 'DNS Configuration', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Government Digital Identity', 'SSL / TLS Certificates', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Government Digital Identity', 'Domain Governance Framework', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Government Digital Identity', 'Domain Renewal & Monitoring Schedule', True, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Government Email System', 'info@clet.gov.gh', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Government Email System', 'support@clet.gov.gh', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Government Email System', 'registrar@clet.gov.gh', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Government Email System', 'accreditation@clet.gov.gh', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Government Email System', 'examinations@clet.gov.gh', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Government Email System', 'board@clet.gov.gh', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Government Email System', 'dg@clet.gov.gh (Director-General mailbox)', True, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Government Email System', 'hr@clet.gov.gh', True, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Government Email System', 'procurement@clet.gov.gh', True, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Government Email System', 'press@clet.gov.gh / communications@clet.gov.gh', True, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Government Email System', 'archive@clet.gov.gh', True, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Email Security', 'SPF (Sender Policy Framework)', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Email Security', 'DKIM (DomainKeys Identified Mail)', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Email Security', 'DMARC Policy', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Email Security', 'MFA (Multi-Factor Authentication) on all accounts', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Email Security', 'Security Monitoring & Alerting', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Email Security', 'Email Archiving & Retention Policy', True, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Email Security', 'Phishing Awareness Training for Staff', True, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Website', 'Official Website (clet.gov.gh)', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Website', 'Accessibility Compliance (WCAG 2.1 AA)', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Website', 'Content Management System (CMS)', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Website', 'News Portal', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Website', 'Publications Portal', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Website', 'Accreditation Portal', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Website', 'Student Portal', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Website', 'Search Functionality', False, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Website', 'Online Contact / Enquiry Forms', True, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Website', 'Freedom of Information (RTI) Request Module', True, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Website', 'Multilingual Accessibility (at minimum Akan/English)', True, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Website', 'Cookie & Privacy Notice', True, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Website', 'Website Disaster Recovery / Backup Protocol', True, 'DTI'),
    (5, 'DIGITAL GOVERNMENT & ICT ESTABLISHMENT', 'Website', 'Site Map & XML Sitemap for SEO', True, 'DTI'),
    (6, 'SOCIAL MEDIA & DIGITAL COMMUNICATIONS', 'Platform Registration', 'LinkedIn (Institutional Page)', False, 'CCP'),
    (6, 'SOCIAL MEDIA & DIGITAL COMMUNICATIONS', 'Platform Registration', 'Facebook (Official Page)', False, 'CCP'),
    (6, 'SOCIAL MEDIA & DIGITAL COMMUNICATIONS', 'Platform Registration', 'Instagram', False, 'CCP'),
    (6, 'SOCIAL MEDIA & DIGITAL COMMUNICATIONS', 'Platform Registration', 'X (formerly Twitter)', False, 'CCP'),
    (6, 'SOCIAL MEDIA & DIGITAL COMMUNICATIONS', 'Platform Registration', 'YouTube (Official Channel)', False, 'CCP'),
    (6, 'SOCIAL MEDIA & DIGITAL COMMUNICATIONS', 'Platform Registration', 'Threads', False, 'CCP'),
    (6, 'SOCIAL MEDIA & DIGITAL COMMUNICATIONS', 'Platform Registration', 'WhatsApp Channel', False, 'CCP'),
    (6, 'SOCIAL MEDIA & DIGITAL COMMUNICATIONS', 'Platform Registration', 'Telegram Channel', False, 'CCP'),
    (6, 'SOCIAL MEDIA & DIGITAL COMMUNICATIONS', 'Platform Registration', 'TikTok (for public engagement / younger audience)', True, 'CCP'),
    (6, 'SOCIAL MEDIA & DIGITAL COMMUNICATIONS', 'Platform Registration', 'Google Business Profile', True, 'CCP'),
    (6, 'SOCIAL MEDIA & DIGITAL COMMUNICATIONS', 'Governance', 'Social Media Policy', False, 'CCP'),
    (6, 'SOCIAL MEDIA & DIGITAL COMMUNICATIONS', 'Governance', 'Content Calendar', False, 'CCP'),
    (6, 'SOCIAL MEDIA & DIGITAL COMMUNICATIONS', 'Governance', 'Crisis Communication Plan', False, 'CCP'),
    (6, 'SOCIAL MEDIA & DIGITAL COMMUNICATIONS', 'Governance', 'Social Media Verification (Blue Tick / Official Badge on key platforms)', False, 'CCP'),
    (6, 'SOCIAL MEDIA & DIGITAL COMMUNICATIONS', 'Governance', 'Social Media Monitoring & Analytics Setup', True, 'CCP'),
    (6, 'SOCIAL MEDIA & DIGITAL COMMUNICATIONS', 'Governance', 'Designated Social Media Officer / Team', True, 'CCP'),
    (6, 'SOCIAL MEDIA & DIGITAL COMMUNICATIONS', 'Governance', 'Brand Voice Guidelines for Social Media', True, 'CCP'),
    (6, 'SOCIAL MEDIA & DIGITAL COMMUNICATIONS', 'Governance', 'User-Generated Content Policy', True, 'CCP'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Banking', 'Bank of Ghana Account', False, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Banking', 'GCB Account (Operational)', False, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Banking', 'Treasury Arrangements', False, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Banking', 'Signatory Mandates', False, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Banking', 'Petty Cash Account & Procedure', True, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Banking', 'Foreign Currency Account (for international accreditation activities)', True, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Government Compliance', 'Controller and Accountant-General Registration', False, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Government Compliance', 'GIFMIS Access & Configuration', False, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Government Compliance', 'Ministry of Finance Approval', False, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Government Compliance', 'Budget Approval (Annual & Medium-Term)', False, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Government Compliance', 'Ghana Revenue Authority (GRA) Registration / TIN', True, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Government Compliance', 'SSNIT Employer Registration', True, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Government Compliance', 'Public Procurement Authority (PPA) Registration', True, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Government Compliance', 'Audit Service Notification & Relationship Establishment', True, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Financial Controls', 'Financial Manual', False, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Financial Controls', 'Procurement Manual', False, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Financial Controls', 'Asset Management Framework', False, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Financial Controls', 'Audit Framework', False, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Financial Controls', 'Chart of Accounts', True, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Financial Controls', 'Internal Audit Unit Establishment', True, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Financial Controls', 'Annual Budget Template & Schedule', True, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Financial Controls', 'Financial Reporting Calendar', True, 'FRM'),
    (7, 'FINANCE & PUBLIC SECTOR COMPLIANCE', 'Financial Controls', 'Grant & IGF Management Framework', True, 'FRM'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Foundational / Infrastructure Systems', 'Identity & Access Management (IAM)', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Foundational / Infrastructure Systems', 'Data Warehouse / Enterprise Data Platform', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Foundational / Infrastructure Systems', 'Enterprise Service Bus (ESB) / Integration Layer', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Foundational / Infrastructure Systems', 'API Management Layer / API Gateway', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Foundational / Infrastructure Systems', 'Cybersecurity Platform', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Foundational / Infrastructure Systems', 'Audit Logging Platform (SIEM)', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Foundational / Infrastructure Systems', 'Unified Communications Platform', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Foundational / Infrastructure Systems', 'Cloud Infrastructure Setup & Configuration', True, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Foundational / Infrastructure Systems', 'Disaster Recovery Infrastructure', True, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Foundational / Infrastructure Systems', 'Network Infrastructure (LAN/WAN/VPN)', True, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Foundational / Infrastructure Systems', 'Data Centre / Hosting Arrangements', True, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Core Enterprise Systems', 'ERP (Enterprise Resource Planning)', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Core Enterprise Systems', 'HRMS (Human Resource Management System)', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Core Enterprise Systems', 'Finance System', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Core Enterprise Systems', 'Procurement System', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Core Enterprise Systems', 'Asset Management System', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Core Enterprise Systems', 'Helpdesk / IT Service Management System', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Core Enterprise Systems', 'Records Management System', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Core Enterprise Systems', 'Digital Archives System', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Core Enterprise Systems', 'Document Management System (DMS)', True, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Core Enterprise Systems', 'Correspondence & Registry Tracking System', True, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Education & Academic Systems', 'Student Management System (SMS)', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Education & Academic Systems', 'Admissions System', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Education & Academic Systems', 'Registration System', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Education & Academic Systems', 'Learning Management System (LMS)', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Education & Academic Systems', 'Attendance Management System', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Education & Academic Systems', 'Examination Management System', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Education & Academic Systems', 'CBT (Computer-Based Testing) Platform', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Education & Academic Systems', 'Results Management System', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Education & Academic Systems', 'Certification & Transcript System', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Education & Academic Systems', 'Academic Calendar Management System', True, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Education & Academic Systems', 'Plagiarism Detection System', True, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Education & Academic Systems', 'Timetabling & Scheduling System', True, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Education & Academic Systems', 'e-Library / Digital Repository', True, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Accreditation & Quality Systems', 'Accreditation Portal', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Accreditation & Quality Systems', 'Institutional Compliance Portal', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Accreditation & Quality Systems', 'Inspectorate Platform', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Accreditation & Quality Systems', 'Quality Assurance Platform', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Accreditation & Quality Systems', 'Audit Portal', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Accreditation & Quality Systems', 'Accreditation Status Tracking Dashboard', True, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Accreditation & Quality Systems', 'Continuing Legal Education (CLE) Tracking System', True, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Governance & Management Systems', 'Board Management System', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Governance & Management Systems', 'Committee Management System', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Governance & Management Systems', 'Policy Management System', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Governance & Management Systems', 'Risk Management System', False, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Governance & Management Systems', 'Performance Management System', True, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Governance & Management Systems', 'Business Intelligence / Reporting Dashboard', True, 'DTI'),
    (8, 'DIGITAL TRANSFORMATION & SYSTEMS ESTATE', 'Governance & Management Systems', 'Contract Management System', True, 'DTI'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'GSL Legacy Digitisation – Academic Records', 'Admissions Records', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'GSL Legacy Digitisation – Academic Records', 'Student Files', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'GSL Legacy Digitisation – Academic Records', 'Registration Records', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'GSL Legacy Digitisation – Academic Records', 'Examination Records', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'GSL Legacy Digitisation – Academic Records', 'PLC (Professional Law Course) Records', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'GSL Legacy Digitisation – Academic Records', 'National Bar Examination Records', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'GSL Legacy Digitisation – Academic Records', 'Graduation Records', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'GSL Legacy Digitisation – Academic Records', 'Academic Transcripts', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'GSL Legacy Digitisation – Academic Records', 'Certificates', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'GSL Legacy Digitisation – Academic Records', 'Dissertation & Thesis Repository', True, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Institutional Records', 'Board Minutes', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Institutional Records', 'Committee Minutes', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Institutional Records', 'Policy Documents', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Institutional Records', 'Historical Reports', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Institutional Records', 'Strategic Plans', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Institutional Records', 'Annual Reports', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Institutional Records', 'Correspondence Archives (incoming & outgoing)', True, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Institutional Records', 'Legal Instruments & Court Records relating to legal education', True, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Financial Records', 'Historical Financial Statements', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Financial Records', 'Audit Reports', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Financial Records', 'Procurement Files', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Financial Records', 'Asset Registers', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Financial Records', 'Payroll History', True, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Human Resource Records', 'Staff Files', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Human Resource Records', 'Payroll Records', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Human Resource Records', 'Training Records', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Human Resource Records', 'Disciplinary Records (with appropriate access controls)', True, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Human Resource Records', 'Retired / Emeritus Staff Records', True, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Library & Research Archives', 'Historical Publications', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Library & Research Archives', 'Journals', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Library & Research Archives', 'Research Papers', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Library & Research Archives', 'Legal Education Archives', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Library & Research Archives', 'Historical Photographs', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Library & Research Archives', 'Institutional Media', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Library & Research Archives', 'Law Reform Commission Submissions relating to legal education', True, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Library & Research Archives', 'External Accreditation & Evaluation Reports', True, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Digital Preservation', 'Scanning Programme', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Digital Preservation', 'Indexing Programme', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Digital Preservation', 'Metadata Standards', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Digital Preservation', 'Digital Preservation Policy', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Digital Preservation', 'Archive Search Engine', False, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Digital Preservation', 'Off-site Backup of Digital Archive', True, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Digital Preservation', 'Access Control & Classification Framework for Archives', True, 'LRKS'),
    (9, 'NATIONAL LEGAL EDUCATION DIGITAL ARCHIVE', 'Digital Preservation', 'Records Retention & Disposal Schedule', True, 'LRKS'),
    (10, 'MOBILE APPLICATIONS', 'Applications', 'CLET Mobile App (Public-facing)', False, 'DTI'),
    (10, 'MOBILE APPLICATIONS', 'Applications', 'Student App', False, 'DTI'),
    (10, 'MOBILE APPLICATIONS', 'Applications', 'Accreditation App', False, 'DTI'),
    (10, 'MOBILE APPLICATIONS', 'Applications', 'Inspectorate App', False, 'DTI'),
    (10, 'MOBILE APPLICATIONS', 'Applications', 'Staff App', False, 'DTI'),
    (10, 'MOBILE APPLICATIONS', 'Applications', 'Alumni App', True, 'DTI'),
    (10, 'MOBILE APPLICATIONS', 'Applications', 'Bar Exam Candidate App', True, 'DTI'),
    (10, 'MOBILE APPLICATIONS', 'Store Registration & Compliance', 'Google Play Developer Account', False, 'DTI'),
    (10, 'MOBILE APPLICATIONS', 'Store Registration & Compliance', 'Apple Developer Account', False, 'DTI'),
    (10, 'MOBILE APPLICATIONS', 'Store Registration & Compliance', 'Google Play Store Publication', False, 'DTI'),
    (10, 'MOBILE APPLICATIONS', 'Store Registration & Compliance', 'Apple App Store Publication', False, 'DTI'),
    (10, 'MOBILE APPLICATIONS', 'Store Registration & Compliance', 'Application Security Certification', False, 'DTI'),
    (10, 'MOBILE APPLICATIONS', 'Store Registration & Compliance', 'App Privacy Policy Publication', True, 'DTI'),
    (10, 'MOBILE APPLICATIONS', 'Store Registration & Compliance', 'App Accessibility Compliance', True, 'DTI'),
    (10, 'MOBILE APPLICATIONS', 'Store Registration & Compliance', 'App Version Management & Release Process', True, 'DTI'),
    (11, 'CYBERSECURITY & DATA PROTECTION', 'Policies & Frameworks', 'Cybersecurity Policy', False, 'CA'),
    (11, 'CYBERSECURITY & DATA PROTECTION', 'Policies & Frameworks', 'Data Protection Framework', False, 'CA'),
    (11, 'CYBERSECURITY & DATA PROTECTION', 'Policies & Frameworks', 'Data Protection Commission (DPC) Registration', False, 'CA'),
    (11, 'CYBERSECURITY & DATA PROTECTION', 'Policies & Frameworks', 'Security Operations Centre (SOC)', False, 'CA'),
    (11, 'CYBERSECURITY & DATA PROTECTION', 'Policies & Frameworks', 'Vulnerability Management Programme', False, 'CA'),
    (11, 'CYBERSECURITY & DATA PROTECTION', 'Policies & Frameworks', 'Penetration Testing (Annual)', False, 'CA'),
    (11, 'CYBERSECURITY & DATA PROTECTION', 'Policies & Frameworks', 'Security Awareness Training Programme', False, 'CA'),
    (11, 'CYBERSECURITY & DATA PROTECTION', 'Policies & Frameworks', 'Incident Response Plan', False, 'CA'),
    (11, 'CYBERSECURITY & DATA PROTECTION', 'Policies & Frameworks', 'Business Continuity Plan (BCP)', False, 'CA'),
    (11, 'CYBERSECURITY & DATA PROTECTION', 'Policies & Frameworks', 'Disaster Recovery Plan (DRP)', False, 'CA'),
    (11, 'CYBERSECURITY & DATA PROTECTION', 'Policies & Frameworks', 'Acceptable Use Policy (AUP)', True, 'CA'),
    (11, 'CYBERSECURITY & DATA PROTECTION', 'Policies & Frameworks', 'Third-Party / Vendor Security Assessment Framework', True, 'CA'),
    (11, 'CYBERSECURITY & DATA PROTECTION', 'Policies & Frameworks', 'Cloud Security Policy', True, 'CA'),
    (11, 'CYBERSECURITY & DATA PROTECTION', 'Policies & Frameworks', 'Privacy Impact Assessment (PIA) Template & Process', True, 'CA'),
    (11, 'CYBERSECURITY & DATA PROTECTION', 'Policies & Frameworks', 'Data Classification & Handling Policy', True, 'CA'),
    (11, 'CYBERSECURITY & DATA PROTECTION', 'Policies & Frameworks', 'Personal Data Processing Records (GDPR / Data Protection Act 843)', True, 'CA'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Establishment & Structure', 'Approved Organisational Structure', False, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Establishment & Structure', 'Scheme of Service', False, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Establishment & Structure', 'Conditions of Service', False, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Establishment & Structure', 'Job Descriptions (all roles)', False, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Establishment & Structure', 'Staff Grading & Pay Structure', False, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Establishment & Structure', 'Establishment Register (authorised posts)', True, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Recruitment & Onboarding', 'Recruitment & Selection Policy', False, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Recruitment & Onboarding', 'Advertised Vacancies / Appointment of Foundational Staff', False, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Recruitment & Onboarding', 'Onboarding Programme', False, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Recruitment & Onboarding', 'Staff Induction Manual', False, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Recruitment & Onboarding', 'Probation Policy & Procedure', True, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Recruitment & Onboarding', 'HR Information System (HRIS) Setup', True, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Performance & Development', 'Performance Management System', False, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Performance & Development', 'Annual Performance Appraisal Cycle', False, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Performance & Development', 'Training & Capacity Building Framework', False, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Performance & Development', 'Succession Planning Framework', True, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Performance & Development', 'Leadership Development Programme', True, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Performance & Development', 'Staff Welfare & Employee Assistance Programme', True, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Compliance', 'HR Policies Register', False, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Compliance', 'Labour Act Compliance Checklist', False, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Compliance', 'Staff Disciplinary Procedures', False, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Compliance', 'Grievance & Appeals Procedures', True, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Compliance', 'Equal Opportunities & Non-Discrimination Policy', True, 'PTC'),
    (12, 'HUMAN RESOURCES & ORGANISATIONAL DEVELOPMENT', 'Compliance', 'Anti-Sexual Harassment Policy', True, 'PTC'),
    (13, 'PUBLIC ENGAGEMENT & REPUTATION MANAGEMENT', 'Launch Activities', 'National Launch Event', False, 'CCP'),
    (13, 'PUBLIC ENGAGEMENT & REPUTATION MANAGEMENT', 'Launch Activities', 'Press Conference', False, 'CCP'),
    (13, 'PUBLIC ENGAGEMENT & REPUTATION MANAGEMENT', 'Launch Activities', 'Media Briefings', False, 'CCP'),
    (13, 'PUBLIC ENGAGEMENT & REPUTATION MANAGEMENT', 'Launch Activities', 'Stakeholder Engagement Sessions', False, 'CCP'),
    (13, 'PUBLIC ENGAGEMENT & REPUTATION MANAGEMENT', 'Launch Activities', 'Parliamentary / Committee Briefing', True, 'CCP'),
    (13, 'PUBLIC ENGAGEMENT & REPUTATION MANAGEMENT', 'Launch Activities', 'Legal Professional Bodies Briefing (GBA, CHRAJ, AG Dept etc.)', True, 'CCP'),
    (13, 'PUBLIC ENGAGEMENT & REPUTATION MANAGEMENT', 'Communications Collateral', 'Institutional Profile', False, 'CCP'),
    (13, 'PUBLIC ENGAGEMENT & REPUTATION MANAGEMENT', 'Communications Collateral', 'Fact Sheets', False, 'CCP'),
    (13, 'PUBLIC ENGAGEMENT & REPUTATION MANAGEMENT', 'Communications Collateral', 'FAQs (General & Sector-specific)', False, 'CCP'),
    (13, 'PUBLIC ENGAGEMENT & REPUTATION MANAGEMENT', 'Communications Collateral', 'Press Kit', False, 'CCP'),
    (13, 'PUBLIC ENGAGEMENT & REPUTATION MANAGEMENT', 'Communications Collateral', 'Stakeholder Briefing Packs', True, 'CCP'),
    (13, 'PUBLIC ENGAGEMENT & REPUTATION MANAGEMENT', 'Communications Collateral', 'Legal Education Reform Summary (layperson version)', True, 'CCP'),
    (13, 'PUBLIC ENGAGEMENT & REPUTATION MANAGEMENT', 'Public Education', 'Legal Education Reform Campaign', False, 'CCP'),
    (13, 'PUBLIC ENGAGEMENT & REPUTATION MANAGEMENT', 'Public Education', 'University Outreach Programme', False, 'CCP'),
    (13, 'PUBLIC ENGAGEMENT & REPUTATION MANAGEMENT', 'Public Education', 'Stakeholder Roadshows', False, 'CCP'),
    (13, 'PUBLIC ENGAGEMENT & REPUTATION MANAGEMENT', 'Public Education', 'Public Awareness Programme', False, 'CCP'),
    (13, 'PUBLIC ENGAGEMENT & REPUTATION MANAGEMENT', 'Public Education', 'Annual Legal Education Conference', True, 'CCP'),
    (13, 'PUBLIC ENGAGEMENT & REPUTATION MANAGEMENT', 'Public Education', 'Student & Young Lawyers Engagement Programme', True, 'CCP'),
    (14, 'KNOWLEDGE, MEDIA & PUBLIC AUTHORITY', 'Wikipedia Programme', 'Gather Reliable Source References', False, 'CCP'),
    (14, 'KNOWLEDGE, MEDIA & PUBLIC AUTHORITY', 'Wikipedia Programme', 'Build Reference Repository', False, 'CCP'),
    (14, 'KNOWLEDGE, MEDIA & PUBLIC AUTHORITY', 'Wikipedia Programme', 'Develop Draft Content', False, 'CCP'),
    (14, 'KNOWLEDGE, MEDIA & PUBLIC AUTHORITY', 'Wikipedia Programme', 'Create Wikipedia Page (CLET)', False, 'CCP'),
    (14, 'KNOWLEDGE, MEDIA & PUBLIC AUTHORITY', 'Wikipedia Programme', 'Maintain Wikipedia Content', False, 'CCP'),
    (14, 'KNOWLEDGE, MEDIA & PUBLIC AUTHORITY', 'Wikipedia Programme', 'Create Wikipedia Page (Legal Education Act, 2026 – Act 1170)', True, 'CCP'),
    (14, 'KNOWLEDGE, MEDIA & PUBLIC AUTHORITY', 'Publications', 'National Newspaper Articles', False, 'CCP'),
    (14, 'KNOWLEDGE, MEDIA & PUBLIC AUTHORITY', 'Publications', 'Legal Journal Articles', False, 'CCP'),
    (14, 'KNOWLEDGE, MEDIA & PUBLIC AUTHORITY', 'Publications', 'Academic Publications', False, 'CCP'),
    (14, 'KNOWLEDGE, MEDIA & PUBLIC AUTHORITY', 'Publications', 'Opinion Pieces', False, 'CCP'),
    (14, 'KNOWLEDGE, MEDIA & PUBLIC AUTHORITY', 'Publications', 'Thought Leadership Series', False, 'CCP'),
    (14, 'KNOWLEDGE, MEDIA & PUBLIC AUTHORITY', 'Publications', 'Annual Legal Education Report (State of Legal Education in Ghana)', True, 'CCP'),
    (14, 'KNOWLEDGE, MEDIA & PUBLIC AUTHORITY', 'Publications', 'CLET Newsletter / Gazette Publication', True, 'CCP'),
    (14, 'KNOWLEDGE, MEDIA & PUBLIC AUTHORITY', 'Media Repository', 'Photography Archive', False, 'CCP'),
    (14, 'KNOWLEDGE, MEDIA & PUBLIC AUTHORITY', 'Media Repository', 'Video Archive', False, 'CCP'),
    (14, 'KNOWLEDGE, MEDIA & PUBLIC AUTHORITY', 'Media Repository', 'Press Archive', False, 'CCP'),
    (14, 'KNOWLEDGE, MEDIA & PUBLIC AUTHORITY', 'Media Repository', 'Publications Archive', False, 'CCP'),
    (14, 'KNOWLEDGE, MEDIA & PUBLIC AUTHORITY', 'Media Repository', 'Hansard / Parliamentary Records relating to Act 1170', True, 'CCP'),
    (14, 'KNOWLEDGE, MEDIA & PUBLIC AUTHORITY', 'Media Repository', 'Media Monitoring & Clipping Service', True, 'CCP'),
    (15, 'MONITORING, EVALUATION & REPORTING', 'Frameworks & Plans', 'M&E Framework', False, 'CA'),
    (15, 'MONITORING, EVALUATION & REPORTING', 'Frameworks & Plans', 'Institutional KPI Registry', False, 'CA'),
    (15, 'MONITORING, EVALUATION & REPORTING', 'Frameworks & Plans', 'Annual Operating Plan (AOP)', False, 'CA'),
    (15, 'MONITORING, EVALUATION & REPORTING', 'Frameworks & Plans', 'Strategic Plan (2026–2030)', False, 'CA'),
    (15, 'MONITORING, EVALUATION & REPORTING', 'Frameworks & Plans', 'Quarterly Performance Reporting Template', True, 'CA'),
    (15, 'MONITORING, EVALUATION & REPORTING', 'Frameworks & Plans', 'Annual Report Template & Production Schedule', True, 'CA'),
    (15, 'MONITORING, EVALUATION & REPORTING', 'Frameworks & Plans', 'Mid-Term Strategic Review Process', True, 'CA'),
    (15, 'MONITORING, EVALUATION & REPORTING', 'Frameworks & Plans', 'Stakeholder Satisfaction Survey Framework', True, 'CA'),
    (15, 'MONITORING, EVALUATION & REPORTING', 'Digital Transformation Programme Monitoring', 'Programme Dashboard (all 13 clusters / 252 systems)', False, 'CA'),
    (15, 'MONITORING, EVALUATION & REPORTING', 'Digital Transformation Programme Monitoring', 'Phase 1 Readiness Tracker (95 systems by 31 July 2026)', False, 'CA'),
    (15, 'MONITORING, EVALUATION & REPORTING', 'Digital Transformation Programme Monitoring', 'Vendor Performance Scorecard (5 towers)', False, 'CA'),
    (15, 'MONITORING, EVALUATION & REPORTING', 'Digital Transformation Programme Monitoring', 'Risk & Issues Register (Programme Level)', False, 'CA'),
    (15, 'MONITORING, EVALUATION & REPORTING', 'Digital Transformation Programme Monitoring', 'Change Management Log', False, 'CA'),
    (15, 'MONITORING, EVALUATION & REPORTING', 'Digital Transformation Programme Monitoring', 'Benefits Realisation Framework', True, 'CA'),
    (15, 'MONITORING, EVALUATION & REPORTING', 'Digital Transformation Programme Monitoring', 'SLA Compliance Reporting', True, 'CA'),
]


async def seed_checklist(db) -> None:
    existing = await db.execute(select(ChecklistItem).limit(1))
    if existing.scalar_one_or_none():
        return

    items = [
        ChecklistItem(
            id=str(uuid.uuid4()),
            item_order=order,
            section_number=sec_num,
            section_title=sec_title,
            subsection=subsec,
            item_text=item_text,
            is_new=is_new,
            directorate=directorate,
            status="Not Started",
            progress_pct=0,
            notes="",
            updated_by="",
        )
        for order, (sec_num, sec_title, subsec, item_text, is_new, directorate)
        in enumerate(CHECKLIST_DATA)
    ]

    db.add_all(items)
    await db.commit()
    print(f"Seeded {len(items)} checklist items.")
